quizzyfy/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutUser, name='logoutUser'),
    path('register/', views.registration_page, name='registration_page'),

]

quizzyfy/quizzyfy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('student/', include('student.urls')),
    path('prof/', include('prof.urls')),
]

quizzyfy/student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
                                # HOME
    path('', views.index, name='index'),
    
                                # EXAM
    path('exams', views.exams, name='exams'),
    path('results', views.results, name='results'),
]

quizzyfy/main/models/results.py
from django.db import models
from django.contrib.auth.models import User

class Exam(models.Model):
    name = models.CharField(max_length=255)
    # Add other fields as needed

class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)

quizzyfy/student/models.py
from django.db import models
from main.models.question import *
from main.models.question_paper import *
from django.contrib.auth.models import User

# Create your models here.
class Stu_Question(Question_DB):
    professor = None
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    choice = models.CharField(max_length=3, default="E")


class StuExam_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    examname = models.CharField(max_length=100)
    qpaper = models.ForeignKey(Question_Paper, on_delete=models.CASCADE, null=True)
    questions = models.ManyToManyField(Stu_Question)
    score = models.IntegerField(default=0)
    completed = models.IntegerField(default=0)


class StuResults_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    exams = models.ManyToManyField(StuExam_DB)

quizzyfy/prof/views/result.py
from django.shortcuts import render
from main.models.results import *
from student.models import StuExam_DB
from django.db.models import Avg

# def view_exam_scores(request, exam_id):
#     # Get the exam
#     #exam = StuExam_DB.objects.filter(pk=exam_id)
#     exam = StuExam_DB.objects.filter(pk=exam_id).values('examname')
#     first_exam = exam[0]  # Get the first dictionary from the queryset
#     examname = first_exam['examname']
#     print(exam)
#     students = StuExam_DB.objects.filter(examname=examname)
#     print(students)
#     #viewExam = StuExam_DB.objects.get(examname=exam.values('examname'), student=student)

#     # Get all scores for the exam
#     #scores = Score.objects.filter(exam=exam)

#     return render(request, 'prof/result/exam_scores.html', {'exam': exam, 'students': students})

def view_exam_scores(request, exam_id):
    # Get the exam
    exam = StuExam_DB.objects.filter(pk=exam_id).first()  # Use first() to get a single instance
    examname = exam.examname

    # Get all students for the exam
    students = StuExam_DB.objects.filter(examname=examname)

    # Calculate average score
    average_score = students.aggregate(Avg('score'))['score__avg']

    # Get top 5 scores
    top_scores = students.order_by('-score')[:5]

    # Get bottom 5 scores
    bottom_scores = students.order_by('score')[:5]

    context = {
        'exam': exam,
        'students': students,
        'average_score': average_score,
        'top_scores': top_scores,
        'bottom_scores': bottom_scores,
    }

    return render(request, 'prof/result/exam_scores.html', context)

def view_exam_results(request):
    # Retrieve all exams (adjust the filter conditions based on your model)
    #exams = Exam.objects.all()
    studentExamList = StuExam_DB.objects.filter(completed=1)

    context = {
        'exams': studentExamList,
        'prof': request.user,  # Assuming you have a user object representing the professor
    }

    return render(request, 'prof/result/exam_results.html', context)

quizzyfy/prof/views/student.py
from django.shortcuts import render
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden


def view_students(request):
    prof = request.user
    return render(request, 'prof/student/view_students.html', {
        'students': User.objects.filter(groups__name='Student'), 'prof': prof
    })
    

quizzyfy/student/views/exams.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from main.models import *
from django.contrib.auth.models import User
from main.models.exam import Exam_Model
from main.models.group import Special_Students
from student.models import *
from django.utils import timezone


def exams(request):
    student = request.user

    studentGroup = Special_Students.objects.filter(students=student)
    studentExamsList = StuExam_DB.objects.filter(student=student)

    if request.method == 'POST' and not request.POST.get('papertitle', False):
        paper = request.POST['paper']
        stuExam = StuExam_DB.objects.get(examname=paper, student=student)
        qPaper = stuExam.qpaper
        examMain = Exam_Model.objects.get(name=paper)

        # TIME COMPARISON
        exam_start_time = examMain.start_time
        curr_time = timezone.now()

        if curr_time < exam_start_time:
            return redirect('student:exams')

        stuExam.questions.all().delete()

        qPaperQuestionsList = qPaper.questions.all()
        for ques in qPaperQuestionsList:
            student_question = Stu_Question(question=ques.question, optionA=ques.optionA, optionB=ques.optionB,
                                            optionC=ques.optionC, optionD=ques.optionD,
                                            answer=ques.answer, student=student)
            student_question.save()
            stuExam.questions.add(student_question)
            stuExam.save()

        stuExam.completed = 1
        stuExam.save()
        mins = examMain.duration
        secs = 0

        return render(request, 'student/paper/viewpaper.html', {
            'qpaper': qPaper, 'question_list': stuExam.questions.all(), 'student': student, 'exam': paper, 'min': mins, 'sec': secs
        })

    elif request.method == 'POST' and request.POST.get('papertitle', False):
        paper = request.POST['paper']
        title = request.POST['papertitle']
        stuExam = StuExam_DB.objects.get(examname=paper, student=student)
        qPaper = stuExam.qpaper

        examQuestionsList = stuExam.questions.all()
        examScore = 0
        for ques in examQuestionsList:
            ans = request.POST.get(ques.question, False)
            if not ans:
                ans = "E"
            ques.choice = ans
            ques.save()
            if ans == ques.answer:
                examScore = examScore + 1

        stuExam.score = examScore
        stuExam.save()

        return render(request, 'student/result/result.html', {
            'Title': title, 'Score': examScore, 'student': student
        })

    return render(request, 'student/exam/viewexam.html', {
        'student': student, 'paper': studentExamsList
    })

quizzyfy/student/views/result.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from main.models import *
from django.contrib.auth.models import User
from main.models.group import Special_Students
from student.models import *


def results(request):
    student = request.user

    studentGroup = Special_Students.objects.filter(students=student)
    studentExamList = StuExam_DB.objects.filter(student=student, completed=1)

    if request.method == 'POST':
        paper = request.POST['paper']
        viewExam = StuExam_DB.objects.get(examname=paper, student=student)
        return render(request, 'student/result/individualresult.html', {
            'exam': viewExam, 'student': student, 'quesn': viewExam.questions.all()
        })

    return render(request, 'student/result/results.html', {
        'student': student, 'paper': studentExamList
    })

quizzyfy/student/templates/student/result/individualresult.html
{% extends 'student/base/base.html' %}

{% block title %}Result{% endblock title %}
{% block nav_title %}{{ exam.examname }}{% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}

{% block body %}
    <div class="container-fluid my-2">
        <h3 align="center">Score : {{ exam.score }}</h3>
        <ol class="list-group">
            {% for ques in quesn %}
            <li class="list-group-item list-group-item-action my-1"><h4>{{ ques.question }}</h4>
                <ul>A. {{ques.optionA}}</ul>
                <ul>B. {{ques.optionB}}</ul>
                <ul>C. {{ques.optionC}}</ul>
                <ul>D. {{ques.optionD}}</ul>
            <br>

            {% if ques.choice != 'E' %}
            <a>Selected Option - {{ques.choice}}</a><br>
            {% endif %}
            <a>Correct answer - {{ques.answer}}</a><br>
            {% if ques.choice == ques.answer and ques.choice != 'E' %}
            <a>Status: Correct</a><br>
            {% elif ques.choice == 'E' %}
            <a>Status: Not attempted</a><br>
            {% else %}
            <a>Status: Wrong</a><br>
            {% endif %}
            </li>
            {% endfor %}
        </ol>
    </div>
{% endblock body %}

quizzyfy/student/templates/student/result/result.html
{% extends 'student/base/base.html' %}

{% block title %}View Paper{% endblock title %}
{% block nav_title %}{{ Title }}{% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}

{% block body %}
    <div class="container-fluid my-2">
        <a href="{%url 'student:results'%}" class="btn btn-primary">Check results</a>
    </div>
{% endblock body %}

quizzyfy/student/templates/student/result/results.html
{% extends 'student/base/base.html' %}

{% block title %}Results{% endblock title %}
{% block nav_title %} Results {% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}

{% block body %}
    <div class="container-fluid my-2">
        <ul class="list-group">
            {% for i in paper %}
                {% if  i.completed == 1 %}
                <li class="list-group-item list-group-item-action my-1"><h5>{{ i.examname }}</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{ i.examname }}" name="paper">
                        <input type="submit" class="btn btn-info" value="View result">
                    </form>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock body %}